### PR TITLE
add label to chosen multi select input

### PR DESCRIPTION
**Pull request by ouhryn**
- [x] @johnny-lai 

issue https://coupadev.atlassian.net/browse/CD-172176
Form element must have labels

solution: added label attributes to chosen multi select input

### CODE REVIEW

**Comment by johnny-lai** [comment]
lgtm

**Comment by ouhryn** [comment]
@johnny-lai please merge this pr. thanks

**Comment by ouhryn** [comment]
@johnny-lai @curtismoore Please merge this PR. thanks

**Comment by johnny-lai** [comment]
[lockit v4.9.2] merged via Lockit CLI on 2019-11-15 15:49:27.825974 -0800 PST m=+5.123688395

**Comment by johnny-lai** [comment]
sorry for the delay. it's merged now.

**Pull request merged**
